name: Main
on: push

env:
  RCLONE_DRIVE_SCOPE: drive
  RCLONE_CONFIG_GDRIVE_TYPE: drive
  TEMP_RCLONE_DIR: /opt/rclone_temp
  GDRIVE_ACCT_FILE: google-echopype.json

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -l {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
            environment-name: build-env
            create-args: >-
                python=3.10
                rclone
                pygithub
            cache-environment: true
            post-cleanup: 'all'
      - name: Check rclone version
        run: rclone version
      - name: Setup rclone temp dir
        run: |
            if [ -d "${{env.TEMP_RCLONE_DIR}}" ]
            then
                echo "${{env.TEMP_RCLONE_DIR}} found."
            else
                echo "creating ${{env.TEMP_RCLONE_DIR}}"
                mkdir ${{env.TEMP_RCLONE_DIR}}
            fi
      - name: Setup service account file env
        run: |
            echo "RCLONE_DRIVE_SERVICE_ACCOUNT_FILE=${{env.TEMP_RCLONE_DIR}}/${{env.GDRIVE_ACCT_FILE}}" >> $GITHUB_ENV
      - name: Get google json file
        run: |
            echo $GDRIVE_JSON | jq . > $RCLONE_DRIVE_SERVICE_ACCOUNT_FILE
        env:
            GDRIVE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON}}
      - name: Check rclone listing
        run: |
            rclone ls gdrive:
        env:
            RCLONE_DRIVE_ROOT_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      - name: Set test data dir
        run: echo "TEST_DATA_FOLDER=${{ github.workspace }}/data" >> $GITHUB_ENV
      - name: Clone test data
        run: |
            echo "Removing old test data"
            rm -rf $TEST_DATA_FOLDER
            echo "Copying new test data from google drive"
            rclone copy gdrive: $TEST_DATA_FOLDER
            echo "Done"

            chmod -R ugoa+w $TEST_DATA_FOLDER
            ls -lah $TEST_DATA_FOLDER
        env:
            RCLONE_DRIVE_ROOT_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      - name: Zip all folders
        shell: python
        run: |
          from pathlib import Path
          import shutil
          import os
          import glob

          test_data_folder = Path(os.environ.get("TEST_DATA_FOLDER"))
          for d in test_data_folder.iterdir():
              # Folders only to zip
              if d.is_dir():
                  shutil.make_archive(d, 'zip', d)
          
          print("Successfully zipped the following files:")
          for f in glob.glob(str((test_data_folder / '*.zip').absolute())):
              print(f)
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.TEST_DATA_FOLDER }}/*.zip
          body_path: ${{ env.TEST_DATA_FOLDER }}/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
